# bus Booking 
#Online payment
import time 
import random
import math
def booking():
    seatbooked=int(input("How many seats do you want to book :"))
    seatleft=random.randint(0,20)
    if seatbooked<=seatleft:
        print("Your seats are getting booked.")
        time.sleep(0.5)
        if seatbooked!=0:
            pay()
    else:
        print("Sorry no seats available")
                
                
def pay():
    print("Enter your choice to pay through UPI:")
    time.sleep(0.3)
    print('''a)Google pay
             b)Paytm
             c)PhonePe
             d)BHIM UPI''')
    b=input()
    if (b=="a"):
        time.sleep(0.2)
        c=input("Enter your Gpay ID:")
        time.sleep(0.2)
        print("Checking your ID")
        time.sleep(0.15)
        print("Confirming  payment")
        time.sleep(0.15)
        print("PROCESSING.")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".")
        time.sleep(1)
        print("payment successfull")
    elif (b=="b"):
        time.sleep(0.2)
        c=input("Enter your Paytm ID:")
        time.sleep(0.1)
        print("Checking your ID")
        time.sleep(0.25)
        print("Confirming  payment")
        time.sleep(0.2)
        print("PROCESSING.")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".")
        time.sleep(1)
        print("payment successfull")
    elif (b=="c"):
        time.sleep(0.2)
        c=input("Enter your PhonePe ID:")
        time.sleep(0.1)
        print("Checking your ID")
        time.sleep(0.25)
        print("Confirming  payment")
        time.sleep(0.2)
        print("PROCESSING.")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".")
        time.sleep(1)
        print("payment successfull")
    elif (b=="d"):
        time.sleep(0.2)
        c=input("Enter your BHIM UPI ID:")
        time.sleep(0.1)
        print("Checking your ID")
        time.sleep(0.25)
        print("Confirming  payment")
        time.sleep(0.2)
        print("PROCESSING.")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".",end="")
        time.sleep(0.25)
        print(".")
        time.sleep(1)
        print("payment successfull")
    else:
        print("pls choose correct option")
        pay()
        
        
#main
while True:
    print("Hello")
    time.sleep(0.5)
    print("Welcome to Travel Agency BUSGO")
    time.sleep(0.5)
    print("Where do you want to go")
    print("a)Himachal Pradesh")
    print("b)Rajasthan")
    print("c)Ludhiana")
    print("d)Delhi")
    print("e)Ambala")
    time.sleep(0.5)
    des=input("Enter your choice")
    time.sleep(0.5)
    if des=="a":                                                         #first city des
        print("Welcome to BUSGO")
        time.sleep(0.5)
        start=input("Enter your location(in capital letters)")
        time.sleep(0.5)
        print("Your Destination is Himachal Pradesh")
        time.sleep(0.5)
        if start=="CHITKARA":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Chandigarh,Rajpura")
            print("Bus no.2 route through Ambala Bypass")
            print("Bus no.3 route through Chandigarh,Sarohapur")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="PANIPAT":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Panipat TOLL")
            print("Bus no.2 route through Panipat Bus Stannd")
            print("Bus no.3 route through Noorvala")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="LUDHIANA":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Ludhiana Bus Stand")
            print("Bus no.2 route through Amar Shaheed sukhdev Interstate Bus Terminal")
            print("Bus no.3 route through ISBT Ludhiana")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="DELHI":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Delhi Bus Stand")
            print("Bus no.2 route through Shivaji Stadium Terminal")
            print("Bus no.3 route through ISBT")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        else:
            print("Sorry We are not yet available in your city")
    elif des=="b":                                                          #second city des
        print("Welcome to BUSGO")
        time.sleep(0.5)
        start=input("Enter your location(in capital letters)")
        time.sleep(0.5)
        print("Your Destination is Rajasthan")
        time.sleep(0.5)
        if start=="CHITKARA":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Chandigarh,Rajpura")
            print("Bus no.2 route through Ambala Bypass")
            print("Bus no.3 route through Chandigarh,Sarohapur")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="PANIPAT":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Panipat TOLL")
            print("Bus no.2 route through Panipat Bus Stannd")
            print("Bus no.3 route through Noorvala")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="LUDHIANA":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Ludhiana Bus Stand")
            print("Bus no.2 route through Amar Shaheed sukhdev Interstate Bus Terminal")
            print("Bus no.3 route through ISBT Ludhiana")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="DELHI":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Delhi Bus Stand")
            print("Bus no.2 route through Shivaji Stadium Terminal")
            print("Bus no.3 route through ISBT")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        else:
            print("Sorry We are not yet available in your city")
    elif des=="c":                                                          #third city des
        print("Welcome to BUSGO")
        time.sleep(0.5)
        start=input("Enter your location(in capital letters)")
        time.sleep(0.5)
        print("Your Destination is Ludhiana")
        time.sleep(0.5)
        if start=="CHITKARA":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Chandigarh,Rajpura")
            print("Bus no.2 route through Ambala Bypass")
            print("Bus no.3 route through Chandigarh,Sarohapur")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="PANIPAT":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Panipat TOLL")
            print("Bus no.2 route through Panipat Bus Stannd")
            print("Bus no.3 route through Noorvala")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="DELHI":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Delhi Bus Stand")
            print("Bus no.2 route through Shivaji Stadium Terminal")
            print("Bus no.3 route through ISBT")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        else:
            print("Sorry We are not yet available in your city")
    elif des=="d":                                                          #fourth city des
        print("Welcome to BUSGO")
        time.sleep(0.5)
        start=input("Enter your location(in capital letters)")
        time.sleep(0.5)
        print("Your Destination is Delhi")
        time.sleep(0.5)
        if start=="CHITKARA":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Chandigarh,Rajpura")
            print("Bus no.2 route through Ambala Bypass")
            print("Bus no.3 route through Chandigarh,Sarohapur")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="PANIPAT":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Panipat TOLL")
            print("Bus no.2 route through Panipat Bus Stannd")
            print("Bus no.3 route through Noorvala")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="LUDHIANA":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Ludhiana Bus Stand")
            print("Bus no.2 route through Amar Shaheed sukhdev Interstate Bus Terminal")
            print("Bus no.3 route through ISBT Ludhiana")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        else:
            print("Sorry We are not yet not available in your city")
    elif des=="e":                                                          #fivth city des
        print("Welcome to BUSGO")
        time.sleep(0.5)
        start=input("Enter your location(in capital letters)")
        time.sleep(0.5)
        print("Your Destination is Ambala")
        time.sleep(0.5)
        if start=="CHITKARA":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Chandigarh,Rajpura")
            print("Bus no.2 route through Ambala Bypass")
            print("Bus no.3 route through Chandigarh,Sarohapur")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="PANIPAT":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Panipat TOLL")
            print("Bus no.2 route through Panipat Bus Stannd")
            print("Bus no.3 route through Noorvala")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="LUDHIANA":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Ludhiana Bus Stand")
            print("Bus no.2 route through Amar Shaheed sukhdev Interstate Bus Terminal")
            print("Bus no.3 route through ISBT Ludhiana")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        elif start=="DELHI":
            print("Finding Busses for you .",end="")
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",end='')
            time.sleep(0.5)
            print(".",)
            print("Bus no.1 route through Delhi Bus Stand")
            print("Bus no.2 route through Shivaji Stadium Terminal")
            print("Bus no.3 route through ISBT")
            busno=int(input("Enter the BUS NO. you choose to go:"))
            time.sleep(0.5)
            booking()
        else:
            print("Sorry We are not yet available in your city")
    else:
        print("Sorry We are not yet available in your city")
        
